name: scandium
description: Real time chat project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:

  uuid: ^3.0.0
  bloc: ^8.1.0
  equatable: ^2.0.3
  flutter_bloc: ^8.1.1
  formz: ^0.4.0
  dio: ^5.1.1
  shared_preferences: ^2.1.0
  jwt_decoder: ^2.0.1
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  intl: ^0.17.0
  flutter_guid: ^0.3.1
  sticky_grouped_list: ^3.1.0
  signalr_netcore: ^1.2.4
  easy_localization: ^3.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/translations/
